### ISSUE TITLE
Connect personal node?

### ISSUE THREAD

**Issue by thibistaken** [Blockstream/green_qt#30] opened 2020-05-25 10:55 UTC
It would be great to have a way to connect a node running on my own hardware for better privacy.

**Comment by RolfHodl** [comment] 2020-05-28 21:29
Also like this idea - and make tor an opt out option for later in the settings please if your network changes where TOR is blocked.

**Comment by Furunodo** [comment] 2020-05-30 12:36
duplicate of https://github.com/Blockstream/green_qt/issues/16

**Comment by domegabri** [comment] 2020-06-01 13:58
yes, I left an answer in #16. Definitely a goal after support for single signature wallets

**Comment by domegabri** [comment] 2023-03-07 21:48
You can now connect to your personal electrum server.

**Closed by domegabri** 2023-03-07 21:48 UTC
Labels: duplicate
