### ISSUE TITLE
AppImage not launching after update from 1.1.8 to 1.2.0

### ISSUE THREAD

**Issue by mattkwarren** [Blockstream/green_qt#82] opened 2023-05-19 02:08 UTC
### Version
1.2.0 (AppImage)

### Steps to reproduce

Try to launch the application

### Expected behaviour

The application should launch

The application never launches, even after complete removal, resinstallation, and machine restart and updates.

### Device or machine

Fedora 37

**Comment by borgbyte** [comment] 2023-05-19 22:00
I think the issue is:
 - you are running Wayland, check `echo $XDG_SESSION_TYPE`
 - in that case Green/Qt will use Wayland QPA plugin
 - looks like there are some issues regarding Wayland and AppImage
 
Try the following workaround for now:
```sh
QT_QPA_PLATFORM=xcb ./BlockstreamGreen-x86_64.AppImage`
```

**Comment by mattkwarren** [comment] 2023-05-19 22:20
The root issue is that the previous version worked on the exact same system that the update doesn't work on. I was always running Wayland, as most modern GNU/Linux systems do at this point. Shouldn't the update run fine without user input? The Green AppImage is the only variable that has changed, so I don't see how that suggests an issue with AppImage or Wayland. I appreciate the workaround though. For the record, it didn't work.

**Comment by borgbyte** [comment] 2023-05-19 23:01
> Shouldn't the update run fine without user input?

Yes, it will be fixed in the next release.

> The Green AppImage is the only variable that has changed

Yes, here are the changes the caused this issue:
 - before: qt 5.15.2 and the official build only included xcb qpa plugin
 - now: qt 6.4.2 and both xcb and wayland plugins are builtin in the official binary.

Internally Qt will pick the qpa plugin according to the environment, and it's selecting wayland. But seems that you are experiencing similar issues as:

https://github.com/moonlight-stream/moonlight-qt/issues/916
https://github.com/cnr-isti-vclab/meshlab/issues/738

> For the record, it didn't work.

Not sure if you noticed a typo in the workaround command, if not please try again.

**Comment by borgbyte** [comment] 2023-07-01 20:43
@mattkwarren I believe this has been fixed, please reopen otherwise. Just update to 1.2.3. You can also get the flatpak https://flathub.org/apps/com.blockstream.Green

**Closed by borgbyte** 2023-07-01 20:43 UTC

**Comment by darosior** [comment] 2024-04-06 11:38
I'm getting the same issue with version 2.0.3 here. The workaround doesn't work for me too.

```
$ QT_QPA_PLATFORM=xcb ./BlockstreamGreen-x86_64.AppImage 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted
```

Trying to use 1.1.8 just in case i don't get the error message but it still aborts:
```
$ QT_QPA_PLATFORM=xcb ./BlockstreamGreen-x86_64\(2\).AppImage 
Aborted
```

**Comment by borgbyte** [comment] 2024-04-10 06:41
@darosior please install libxcb-cursor0 and try again.
