### ISSUE TITLE
Cannot build green - ./tools/buildgreen.sh: line 4: tools/envs.env: No such file or directory

### ISSUE THREAD

**Issue by eckelj** [Blockstream/green_qt#114] opened 2024-03-12 16:33 UTC
### Description
I am trying to investigate a bug that I am experiencing with green. Therefore, I try to build the solution but fail.

### Version

master: https://github.com/Blockstream/green_qt/commit/d6dd29941f66e6060b466792249d901d45da72e8

### Steps to reproduce
I am following the instructions of the Readme/build
```
git clone git@github.com:Blockstream/green_qt.git
cd green_qt
docker run -v $PWD:/ga greenaddress/ci@sha256:c9c0bfc0eef0575d5822f9308ab16ff904a8bf99946c67938dd7637d70998220 /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux allsymbolsunstripped && cp /docker_bld_root/build-linux-gcc/green /ga/green"
```

### Expected behaviour

It starts building the app in docker. 

### Actual behaviour
build process quits directly with the error that tools/evns.env is not found. 
```
➜  green_qt git:(master) docker run -v $PWD:/ga greenaddress/ci@sha256:c9c0bfc0eef0575d5822f9308ab16ff904a8bf99946c67938dd7637d70998220 /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux allsymbolsunstripped && cp /docker_bld_root/build-linux-gcc/green /ga/green"
./tools/buildgreen.sh: line 4: tools/envs.env: No such file or directory
```

### Device or machine

ubuntu

**Comment by eckelj** [comment] 2024-03-12 19:21
this one here: https://github.com/Blockstream/green_qt/issues/95

**Comment by eckelj** [comment] 2024-03-12 19:22
btw. thx! I aam looking forward to the updated instructions!

**Comment by borgbyte** [comment] 2024-03-12 23:05
Duplicate of #90.

**Closed by borgbyte** 2024-03-12 23:05 UTC
